// Code generated by orvex-studio-contracts gen/go from the declaration plane.
// DO NOT EDIT — regenerate via `go run ./gen/go` (regen-diff gated, Spine AD-5).
//
// orvex-wiki
//
// The AD-2 SUBSTRATE BAN config, TypeScript half (RULE 4 polyglot
// parity), materialised from gates/eslint/restrictions.yaml with every exemption
// resolved from config/services.yaml lint.* — the single oracle. Edit the DATA in
// orvex-studio-contracts, never this file.
//
// DRIFT: a hand-edit of this committed copy is caught by the substrate-lint-drift
// check, which holds it against the content hash this generator recorded:
//   - private repo: call the reusable workflow
//       uses: orvexai/orvex-studio-contracts/.github/workflows/substrate-lint-drift.yml@<tag>
//   - public repo (cannot call a private reusable workflow): commit the emitted
//       substrate-lint-drift.sh and run it as a CI step.
// Inside orvex-studio-contracts the same drift reds `make gen-go` (regen-diff).
// ADOPTING THIS FILE WITHOUT THAT CHECK IS AN INCOMPLETE ADOPTION — the config
// then enforces the bans but nothing enforces the config (gates/lint/README.md).
//
// It uses CORE ESLint rules only (no ESLint PLUGIN), so it runs beside a repo's
// own full-scope config without adopting that repo's ruleset:
//   npx eslint --config eslint.substrate.config.mjs <files>
//
// PREREQUISITE — the TypeScript PARSER. That command works only once this repo
// carries "typescript-eslint" as a devDependency. ESLint's default parser (espree)
// cannot parse TypeScript, and a file that FAILS TO PARSE has no rule evaluated:
// without the parser this config reports parse errors and ZERO ban findings —
// indistinguishable from a clean run. So it is imported below and this file
// THROWS when it is missing or is not ESLint-shaped. It never falls back.
//
// RATCHET (PO ruling PO-2026-07-29-5, applied verbatim): ESLint has no built-in
// ratchet, so the equivalent is an INVOCATION contract, not a config key —
// mode `changed-files-vs-base`: pass only the files this branch changed relative to
// origin/dev, e.g.
//   git diff --name-only --diff-filter=d $(git merge-base HEAD origin/dev) | \
//     xargs -r npx eslint --config eslint.substrate.config.mjs --no-error-on-unmatched-pattern
// Regen-diff protection and every other lint/CI run stay FULL-SCOPE.
// Removing this ratchet (flip ratchet.status to `retired` here and
// regenerate) is a REQUIRED item of the service's Phase-2 adoption DoD.
//
// INLINE CONFIG: FORBIDDEN (gates/lint/materialisation.yaml eslint.inline_config)
// — `linterOptions.noInlineConfig: true` below. An ESLint directive comment
// CANNOT disable a substrate ban: without this, one
// `/* eslint-disable no-restricted-properties */` at the top of a file disarms
// the ban for that whole file with no trace in the declaration plane. The only
// ways out of a ban are DATA — the owner markers, the per-service exemption and
// the test surfaces, all resolved above.
// It is also what makes this config safe to run BESIDE the repo's own: a
// directive naming a rule from the repo's own plugin set (this config registers
// no plugin) used to report `Definition for rule ... was not found` — an ERROR
// on a line the branch never wrote, which the changed-files ratchet then made
// unmergeable. Now it is a severity-1 advisory and the run exits 0.
// Passing `--no-inline-config` on the command line as well is redundant but
// harmless: it silences those advisories.
//
// TEST SURFACES (ENG-3328) — the trailing override block below stands these
// restrictions down inside the globs declared at lint.test_surfaces, because a
// test that stands up a server MUST exercise the unconfigured path the ban's own
// remedy forbids. Every OTHER ban on the same mechanism is re-declared inside
// that block, so this can never widen past the restrictions named here:
//   - process-env
//
// NOT ENFORCED BY THIS FILE — derived per restriction from the declaration plane
// (id — disposition), never a blanket sentence. PO-2026-07-29-9: a restriction
// flips pending -> active PER RULE, as ITS mechanism ships; until then it is
// named here with the enforcer that holds the line today:
//   - blackbox-import-boundary — status: pending (mechanism
//     "no-restricted-imports" has not shipped for this surface); enforced
//     today by scripts/blackbox_boundary_gate.py (contracts-internal tree
//     gates/conform/blackbox/**; no consuming repo runs it)

import tseslint from "typescript-eslint";

const substrateParser = tseslint?.parser;
if (
  !substrateParser ||
  (typeof substrateParser.parseForESLint !== "function" &&
    typeof substrateParser.parse !== "function")
) {
  throw new Error(
    "the AD-2 substrate ban config needs the declared TypeScript parser tseslint.parser from " +
      "typescript-eslint, which did not resolve to an ESLint parser. There is NO fallback and " +
      "this is not optional: espree cannot parse TypeScript, an unparseable file has no " +
      "rule evaluated, and the run would report ZERO ban findings — a green that means " +
      "nothing. Add typescript-eslint to this repo's devDependencies (gates/lint/README.md).",
  );
}

export default [
  {
    files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cjs"],
    languageOptions: {
      parser: substrateParser,
    },
    linterOptions: {
      noInlineConfig: true,
    },
    rules: {
      "no-restricted-properties": [
        "error",
        {
          object: "process",
          property: "env",
          message: "process.env is the TS analogue of os.Getenv — load typed config through @orvexai/contracts.loadConfig (config/services.yaml lint.substrate_allow.config_ts), never a bare process.env read. In a PUBLIC repo, which cannot consume the private @orvexai/contracts package at all, that remedy is unreachable: declare the path in config/services.yaml services.<repo>.lint.env_read_paths instead — a per-service exemption, never a widening of the family-fixed marker. Test surfaces are exempted via lint.test_surfaces.",
        },
      ],
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "jose",
              message: "A browser/extension surface must not import a JWT/JOSE library (AD-9) — identity is verified once at the edge; the only auth peer is @orvexai/auth-node on the server tier.",
            },
            {
              name: "jsonwebtoken",
              message: "A browser/extension surface must not import a JWT/JOSE library (AD-9) — identity is verified once at the edge; the only auth peer is @orvexai/auth-node on the server tier.",
            },
            {
              name: "jwks-rsa",
              message: "A browser/extension surface must not import a JWT/JOSE library (AD-9) — identity is verified once at the edge; the only auth peer is @orvexai/auth-node on the server tier.",
            },
            {
              name: "@panva/jose",
              message: "A browser/extension surface must not import a JWT/JOSE library (AD-9) — identity is verified once at the edge; the only auth peer is @orvexai/auth-node on the server tier.",
            },
            {
              name: "jwt-decode",
              message: "A browser/extension surface must not import a JWT/JOSE library (AD-9) — identity is verified once at the edge; the only auth peer is @orvexai/auth-node on the server tier.",
            },
            {
              name: "@clerk/backend",
              message: "A browser/extension surface must not import a JWT/JOSE library (AD-9) — identity is verified once at the edge; the only auth peer is @orvexai/auth-node on the server tier.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["scripts/**"],
    // scripts is the declared owner of: process-env.
    rules: {
      "no-restricted-properties": "off",
    },
  },
  {
    files: ["src/config/**"],
    // src/config is the declared owner of: process-env.
    rules: {
      "no-restricted-properties": "off",
    },
  },
  {
    files: ["pkg/auth/**"],
    // pkg/auth is the declared owner of: browser-jwt-jose.
    rules: {
      "no-restricted-imports": "off",
    },
  },
  {
    files: ["apps/server/src/orvex/config/**"],
    // apps/server/src/orvex/config is the declared owner of: process-env.
    rules: {
      "no-restricted-properties": "off",
    },
  },
  {
    files: [
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/*.test.mts",
      "**/*.test.cts",
      "**/*.test.js",
      "**/*.test.jsx",
      "**/*.test.mjs",
      "**/*.test.cjs",
      "**/*.spec.ts",
      "**/*.spec.tsx",
      "**/*.spec.mts",
      "**/*.spec.cts",
      "**/*.spec.js",
      "**/*.spec.jsx",
      "**/*.spec.mjs",
      "**/*.spec.cjs",
      "**/test/**",
      "**/tests/**",
      "**/e2e/**",
      "**/__tests__/**",
      "**/__mocks__/**",
      "**/__fixtures__/**",
      "**/fixtures/**",
    ],
    // test surfaces (lint.test_surfaces) stand down: process-env.
    rules: {
      "no-restricted-properties": "off",
    },
  },
];

// The TEST SURFACES this config stands process-env down inside
// (config/services.yaml lint.test_surfaces). Not read by ESLint.
export const substrateTestSurfaces = [
  "**/*.test.ts",
  "**/*.test.tsx",
  "**/*.test.mts",
  "**/*.test.cts",
  "**/*.test.js",
  "**/*.test.jsx",
  "**/*.test.mjs",
  "**/*.test.cjs",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/*.spec.mts",
  "**/*.spec.cts",
  "**/*.spec.js",
  "**/*.spec.jsx",
  "**/*.spec.mjs",
  "**/*.spec.cjs",
  "**/test/**",
  "**/tests/**",
  "**/e2e/**",
  "**/__tests__/**",
  "**/__mocks__/**",
  "**/__fixtures__/**",
  "**/fixtures/**",
];
