#!/usr/bin/env bash
# Code generated by orvex-studio-contracts scripts/gen_manifest_copy_check_sh.py
# from .github/workflows/manifest-copy-check.yml. DO NOT EDIT — regenerate via
# `make manifest-copy-standalone` (regen-diff gated, Spine AD-5).
#
# manifest-copy-check, standalone. Byte-identical CHECK to the reusable
# workflow it is derived from; this variant exists for a PUBLIC consuming repo,
# which GitHub does not permit to call a PRIVATE repo's reusable workflow
# (orvex-wiki -> orvex-studio-contracts). ENG-3327.
#
# Adoption: commit this file into the public repo and run it as a CI step whose
# context is in `ci-success.needs` — a gate outside that list is decorative,
# because `ci-success` is the only required status in every repo's ruleset.
#
#     - name: manifest-copy-check (AD-35 regen gate, standalone)
#       run: ./scripts/manifest-copy-check.sh
#
# Re-copy it whenever you repin the contracts tag; the roster inside it is a
# snapshot of my-idp-apps' components/** at the tag this file was cut from.
#
# STATED LIMIT (do not discover this later): because the roster travels WITH
# this file into the consuming repo, this variant closes a hand-edit of a
# materialized component but NOT a two-file edit that also rewrites the digest
# below. A PRIVATE repo must use the reusable workflow, where the roster lives
# in contracts and the consuming repo cannot reach it.
#
# Run from the consuming repo's root.
#   exit 0 = every materialized copy is in sync
#   exit 1 = drift, a stray copy, or a cross-repo `components:` reference
#   exit 2 = cannot rule (refuses to report a verdict it did not earn)
set -uo pipefail
fail=0

# The AD-35 shared-component content-hash roster (see the header
# REGENERATION note). sha256 -> "component/file" label.
# Regenerated 2026-07-30 from orvexai/my-idp-apps@origin/main — all
# 16 tracked components/** files. The previous 11-entry snapshot had
# already rotted again: the five `product-route-middleware/*` files
# (ENG-3070, my-idp-apps e991fcd..4cfcf24) landed after it was taken,
# so owner-mode COMPLETENESS would have red on my-idp-apps' first run.
#
# ENG-3162 (2026-07-30): `external-secrets/kustomization.yaml` moves
# b483d9c0 -> 16e86a5c. my-idp-apps PR #24 changes that component from
# a one-field `replacements:` SOURCE into a strategic-merge `patches:`
# block that SUPPLIES the whole ExternalSecret CRD default set
# (refreshInterval, secretStoreRef.kind/.name, target.creationPolicy,
# target.deletionPolicy). Only this ONE row moves; the other 15 are
# byte-identical, verified by hashing every tracked components/** file
# in that PR's merged tree.
#
# ENG-3296 (2026-07-30): TWO NEW rows, `image-injection/image-ref.yaml`
# and `image-injection/kustomization.yaml` — the shared kustomize
# image-injection component (ENG-3154 T2/AC4), the ONE place a family
# image reference is stamped into a manifest. Every other row is
# byte-identical to the previous snapshot, verified by hashing every
# tracked components/** file in my-idp-apps PR #36's tree. Owner-mode
# COMPLETENESS is why this roster edit is not optional: a components/**
# file with no roster entry reds my-idp-apps' own gate, by design, so a
# new component cannot land ungoverned.
#
# LANDING ORDER — these rows are AHEAD of my-idp-apps `main` on purpose,
# and that is safe only because of how the pin works. main still pins
# manifest-copy-check@v0.51.0 (a roster without the image-injection
# rows), so main stays GREEN. The my-idp-apps PR carries BOTH the new
# component AND the repin to the tag cut from this commit, so the
# roster and the component become true in the same merge. Splitting
# them either way reds the owner leg: repin first and the roster
# describes a component that does not exist yet; merge the component
# first and the pinned roster is stale (here, incomplete). Nothing
# consumes the new tag until that PR merges, so the window is inert.
# The roster cannot carry both hashes for one label — two hashes mapping
# to one label trips the "roster must be a function" refusal below.
declare -A KNOWN_HASHES=(
  ["0e97f6060374cdf08aa1ee118f85b10810c38a765b22daf664faeb94f11ac79e"]="base/kustomization.yaml"
  ["1f2a26ba1d467d2a6c1950021f3bfb27770c4f9c084e45e453629cc89f7f39a4"]="cell-promoted/kustomization.yaml"
  ["addad743bad152d6ef108aba4b36664ca578941bfcf5692fec5f1892766bdb0b"]="cluster-config/configmap.yaml"
  ["f4d99e9a70033673450e7a847645f015823a8e6382d4198bb7af45e73f8c2ee6"]="cluster-config/kustomization.yaml"
  ["d73f23be4a550806f1ad0b526e4165f0cd50f09de76c8bc64c5b0118f8428598"]="external-secrets/configmap.yaml"
  ["16e86a5c94093285ff1a34c111bdec08399fe8800e6ad477234ffd80fce027db"]="external-secrets/kustomization.yaml"
  ["321fc93ca7e7d5ab62e294e67dbd8dbae4c4dd609391ff3086c1b972619f66e8"]="image-injection/image-ref.yaml"
  ["6300e806f078211e44d66042fabb48542d08f7d5407c228765ab71d83c5fbfe6"]="image-injection/kustomization.yaml"
  ["efcd3aae999ed7e1d5cd20a7fa8407fe00866edc1d9db0fab62d4b8d12025c08"]="kafka-topics/kustomization.yaml"
  ["ace05be3c65c129e122022b371d779fe8f8941be3b5fc1245312bb37feedbd10"]="probes/kustomization.yaml"
  ["9758d718e1ce5842782373ca706d700e85916bc14dfa74954bac46c0c78da303"]="product-route-middleware/kustomization.yaml"
  ["a007833b1396b40577f6f80ae9506fcea602a50a0e61c756f07d4852bfe5ad5a"]="product-route-middleware/middleware-buffering.yaml"
  ["209b7ea13f5e4e0f0262a073a9e08ad28885336f83679dd8c2850796ae0c7218"]="product-route-middleware/middleware-ratelimit.yaml"
  ["6ccb21af00a64c147416f2c1a7fb060f7f70b7448c1583d1e2da438965ad13b1"]="product-route-middleware/middleware-security-headers.yaml"
  ["824fe9186912c8fbfd2e1d457bf2d37fe0f1c5940146c4d84d8f3dcc1c134f87"]="product-route-middleware/serverstransport-timeout.yaml"
  ["f633ea08f29045ecfcf1d99b706fade412e24e38ccf281e30e391dc351127688"]="resource-envelopes/kustomization.yaml"
  ["9a668b58a03b3bd8f0136bc9f77f8ec92e9b259515bd266b7b76f6ad5c2cce46"]="telemetry-env/configmap.yaml"
  ["060645f2e6b327d7d59a398d25de66ed5846ee7f68be754a8ce1f444ffafead1"]="telemetry-env/kustomization.yaml"
)

# Which mode this run is in (see the header). The owner is named by
# AD-35 itself, so encoding it here is encoding canon, not a
# special case; `GITHUB_REPOSITORY` is the CALLER's repo for a
# `workflow_call` job, which is exactly the repo whose tree is
# checked out above.
OWNER_REPO="orvexai/my-idp-apps"
is_owner=0
if [ "${GITHUB_REPOSITORY:-}" = "${OWNER_REPO}" ]; then
  is_owner=1
  echo "manifest-copy-check: OWNER mode (${OWNER_REPO}) — asserting the roster still describes components/** exactly."
else
  echo "manifest-copy-check: CONSUMER mode — asserting every materialized components/<label> copy is in sync with the roster (PO-2026-07-30-1)."
fi

# label -> canonical hash, the reverse index the drift check needs:
# given a file sitting at a materialized `**/components/<label>`
# path, what SHOULD its content be? Also serves the owner-mode
# completeness pass (is this components/** file rostered at all?).
#
# A duplicate label would make that reverse index lossy — two hashes
# claiming one label means one of them silently wins and the drift
# check then convicts a correct copy. The roster is generated, so
# this cannot happen by hand-editing alone, but a bad paste can do
# it, and a gate must not be one paste away from accusing the fleet.
declare -A ROSTER_LABELS=()
declare -A SEEN_SOURCE=()
for _h in "${!KNOWN_HASHES[@]}"; do
  _l="${KNOWN_HASHES[$_h]}"
  if [ -n "${ROSTER_LABELS[$_l]:-}" ]; then
    echo "::error::the AD-35 roster carries two hashes for label '${_l}' — it is not a function, so the drift check cannot say what that path should contain; refusing to report a verdict. Regenerate KNOWN_HASHES."
    exit 2
  fi
  ROSTER_LABELS["$_l"]="$_h"
done

# Self-exclude this repo's own fixture trees: they deliberately
# commit a byte-copy of a shared manifest (violations/) so the DoD
# test can prove the rule fails on it (AD-41 reachable negative
# self-test) — same self-exclusion rationale as cell-lint.yml.
# Expressed as a git `:(top,exclude)` pathspec rather than a
# `| grep -v '^...'` filter: the pathspec is repo-root-anchored no
# matter what directory the caller invoked the job from, and `-z`
# keeps the list NUL-separated (the only encoding under which a path
# containing a space or a newline survives — `git ls-files` without
# `-z` C-quotes such paths and the old unquoted `for f in $files`
# word-split them into nonexistent fragments that `[ -f ]` dropped).
#
# The list goes through a temp file rather than
# `mapfile < <(git ls-files ...)` so git's EXIT STATUS is checked
# before the list is trusted. A process substitution's rc is
# unreachable to the reading command, and `set -e` would not have saved
# it either — GitHub's `shell: bash` runs this body as
# `bash --noprofile --norc -eo pipefail`, but `mapfile` itself SUCCEEDS
# (it read an empty stream), so `-e` never sees git's status. This body
# additionally does not add its own `set -e`. Either way the older shape
# could not tell "no tracked file matched" from "git
# failed": a corrupt `.git/index`, a `safe.directory` dubious-ownership
# refusal (a routine self-hosted-runner failure), a missing git, or the
# wrong cwd all yielded an empty list, and the gate then emitted GREEN
# having hashed nothing — with a real vendored copy sitting tracked in
# the tree. Same discipline as the two guards below: refuse to report a
# verdict rather than report one the pass did not earn.
ls_out=$(mktemp) || {
  echo "::error::manifest-copy-check could not create a temp file for the file list; refusing to report a verdict."
  exit 2
}
trap 'rm -f "$ls_out"' EXIT
if ! git ls-files -z -- ':(top)' ':(top,exclude)fixtures/manifest-copy/' > "$ls_out"; then
  echo "::error::manifest-copy-check could not enumerate tracked files (git ls-files exited non-zero); refusing to report a verdict."
  exit 2
fi
mapfile -d '' -t candidates < "$ls_out"

# An enumeration that SUCCEEDED and still found nothing is not a clean
# tree either: this step runs after actions/checkout, and a checkout
# always has tracked files. Zero means the rule is looking at the wrong
# place (empty/partial checkout, wrong working directory), so it has no
# tree to rule on.
if [ "${#candidates[@]}" -eq 0 ]; then
  echo "::error::manifest-copy-check enumerated 0 tracked files — there is no checkout here for it to rule on; refusing to report a verdict."
  exit 2
fi

# Keep only regular files: a tracked gitlink (submodule) or a
# tracked-but-absent path carries no vendorable content. `[ -f ]` is
# a bash builtin, so this pass spawns nothing.
files=()
for f in "${candidates[@]}"; do
  [ -f "$f" ] && files+=("$f")
done

# Distinct from the guard above: the enumeration DID work and every
# path it returned is a gitlink or a tracked-but-absent entry. There is
# genuinely no vendorable content, so this GREEN is earned.
#
# NOT earned in OWNER mode, though: "no regular files" there means
# components/** is absent, and the whole roster is describing
# nothing — the exact rot the owner leg exists to red on.
if [ "${#files[@]}" -eq 0 ]; then
  if [ "$is_owner" -eq 1 ]; then
    echo "::error::OWNER mode found no regular files at all, so none of the ${#KNOWN_HASHES[@]} roster entries can describe a real components/** file — the roster describes nothing."
    exit 1
  fi
  echo "OK: no repo-local copy of a shared manifest found (${#candidates[@]} tracked paths, none of them regular files)."
  exit 0
fi

# ONE batched content-hash pass over the whole file list (ENG-3254).
# The previous shape spawned head + grep + sha256sum + cut PER FILE —
# ~4 processes times every tracked file — so its cost was fork/exec
# bound, not I/O bound, and it blew the DoD test's 30s subprocess
# budget on a loaded runner at ~2.7k tracked files (run 30251837526).
# `xargs -0` hands the list to sha256sum in ARG_MAX-sized batches, so
# the process count is O(total-path-bytes / ARG_MAX) — one batch at
# this repo's size — instead of O(files), and argument order (hence
# error-report order) is preserved.
#
# The AD-2/AD-4 generated-file exemption moved BELOW the hash lookup:
# it can only change the verdict for a file that already hash-matches
# the roster, so evaluating it lazily is behaviour-identical and, on
# a clean tree, spawns nothing at all.
#
# Deliberately still coreutils + bash rather than an inline `python3`
# hashlib pass: this is a `workflow_call` reusable workflow whose
# steps execute on the CALLER's runner, and every python-using
# workflow in this repo has to `actions/setup-python` first — python3
# is not a guaranteed runner capability, so importing it here would
# bolt a network-dependent setup step onto a gate that today needs
# nothing but a shell.
#
# That said, this shape does RAISE the shell floor, so state it rather
# than imply portability it does not have: `mapfile -d ''` needs
# bash >= 4.4 and `sha256sum -z` needs coreutils >= 8.25, both above
# what the pre-ENG-3254 body required. Satisfied by the Linux ARC
# `runners` pool every registered caller runs on; a caller on macOS
# (bash 3.2, no GNU sha256sum) or a busybox image would need its own
# shell. Below the floor `mapfile -d ''` cannot populate `candidates`
# and `set -u` then aborts this body non-zero before any OK line — a
# RED, not a false GREEN.
hashed=0
while IFS= read -r -d '' rec; do
  hashed=$((hashed + 1))
  # `sha256sum -z` emits: 64 hex chars, a space, the mode marker
  # (' ' for text / '*' for binary — NOT necessarily a second space),
  # then the path, then NUL. Both markers are one byte, so ${rec:66}
  # is the path under either; `-z` disables the backslash-escaping
  # that would otherwise shift these offsets for an odd filename.
  h=${rec:0:64}
  f=${rec:66}
  if [[ ! $h =~ ^[0-9a-f]{64}$ ]]; then
    echo "::error::manifest-copy-check could not parse a sha256sum record; refusing to report a verdict."
    exit 2
  fi
  # Classify by PATH first, then by CONTENT — the two questions have
  # different answers under PO-2026-07-30-1 and only the pair of them
  # decides the verdict.
  #
  # path_label: does this file occupy the materialized path of a
  # rostered component? `components/<label>` at the repo root (the
  # owner's own tree) or `<anything>/components/<label>` (a consumer
  # materializing under e.g. deploy/kustomize/components/). The label
  # is the roster's own key, so no new convention is invented here —
  # the materialized path is "…/components/" + the label the roster
  # already uses, which is exactly the path kustomize needs for a
  # `components:` entry to resolve locally.
  path_label=""
  case "$f" in
    components/*)   _cand=${f#components/} ;;
    */components/*) _cand=${f#*/components/} ;;
    *)              _cand="" ;;
  esac
  # `*/components/*` strips at the FIRST match, so a path with two
  # `components/` segments yields the wrong candidate; only accept a
  # candidate the roster actually names, and for anything else fall
  # back to the last `components/` segment before giving up.
  if [ -n "$_cand" ] && [ -z "${ROSTER_LABELS[$_cand]:-}" ]; then
    _tail=${f##*/components/}
    [ -n "${ROSTER_LABELS[$_tail]:-}" ] && _cand=$_tail
  fi
  [ -n "$_cand" ] && [ -n "${ROSTER_LABELS[$_cand]:-}" ] && path_label=$_cand

  label=${KNOWN_HASHES[$h]:-}

  if [ -n "$path_label" ]; then
    # A materialized shared component. Its content MUST be the
    # canonical content — this is the regen-gate leg PO-2026-07-30-1
    # names, and the whole reason a materialized copy is safe to
    # mandate.
    if [ "$label" = "$path_label" ]; then
      # In sync. In the owner repo the same condition identifies the
      # ORIGINAL, which is what the roster-sync pass below consumes.
      [ "$f" = "components/${path_label}" ] && SEEN_SOURCE["$path_label"]=1
      continue
    fi
    if [ "$is_owner" -eq 1 ] && [ "$f" = "components/${path_label}" ]; then
      # The owner's own source file no longer matches its roster pin:
      # the COMPONENT changed and the roster did not follow. The fix
      # is in contracts, not here, so say so — and say it here rather
      # than leaving it to the roster-sync pass, which cannot tell
      # this apart from the file having been deleted.
      echo "::error::components/${path_label} no longer hashes to the roster entry pinned for '${path_label}' — the roster is STALE, so every consumer that correctly re-materialized this component will now be accused of drift (AD-35 roster drift). Regenerate KNOWN_HASHES in orvex-studio-contracts/.github/workflows/manifest-copy-check.yml and cut a contracts tag."
      fail=1
      # Accounted for — already reported, with the right message. The
      # roster-sync pass below must not re-report it as unverified.
      SEEN_SOURCE["$path_label"]=stale
      continue
    fi
    echo "::error::${f} is a materialized copy of shared component '${path_label}' whose content has DRIFTED from the contracts roster (AD-35 / PO-2026-07-30-1)."
    echo "Re-materialize it byte-for-byte from orvexai/my-idp-apps components/${path_label}. If the component itself changed, regenerate KNOWN_HASHES in orvex-studio-contracts and repin this repo's manifest-copy-check ref — do NOT hand-edit the copy."
    fail=1
    continue
  fi

  # Not at a materialized path. Only a CONTENT match matters now.
  [ -n "$label" ] || continue
  # AD-2/AD-4 generated-file exemption: a machine-generated file is
  # not a vendored copy, even if its content happens to hash-match
  # (e.g. a generated config echoing the same defaults).
  if head -n 5 "$f" 2>/dev/null | grep -qE 'Code generated .* DO NOT EDIT'; then
    continue
  fi
  # A byte-copy of a shared component parked somewhere the regen gate
  # does not track. Still a conformance failure, and still the same
  # one AD-35 named — this copy is invisible to the drift leg above,
  # so the day the component changes it silently becomes the stale
  # manifest that actually reaches the cluster.
  echo "::error::${f} is a byte-for-byte copy of shared component '${label}' sitting OUTSIDE a materialized components/${label} path (AD-35 conformance failure)."
  echo "Materialize it as <overlay-root>/components/${label} and reference that path from the overlay's \`components:\` list. Only a copy at that path is tracked by the regen gate; a copy anywhere else drifts unobserved. Do NOT replace it with a cross-repo component reference — ArgoCD drops those silently (PO-2026-07-30-1)."
  fail=1
done < <(printf '%s\0' "${files[@]}" | xargs -0 sha256sum -z --)

# A batched pass can come up short (an xargs batch that failed to
# exec, a file removed mid-run) where the old per-file loop would
# merely have skipped that file. A gate that hashed fewer files than
# it enumerated has stopped checking part of the tree, so refuse to
# report a verdict rather than report a GREEN it did not earn.
if [ "$hashed" -ne "${#files[@]}" ]; then
  echo "::error::manifest-copy-check hashed ${hashed} of ${#files[@]} candidate files — the content-hash pass is incomplete; refusing to report a verdict."
  exit 2
fi

# OWNER mode only — roster-sync. Everything above answers "is any
# file here a copy of the roster?"; this answers the question that
# keeps that first question meaningful: "does the roster still
# describe the components it claims to?" A pinned cross-repo hash
# snapshot rots silently by construction, and a rotted entry does
# not fail — it simply stops matching anything, so the rule reports
# GREEN on a subject it is no longer checking (four of six entries
# were in exactly that state at v0.32.0). Only the owner repo has
# the source tree to detect it, so only the owner asserts it.
if [ "$is_owner" -eq 1 ]; then
  for _h in "${!KNOWN_HASHES[@]}"; do
    _label=${KNOWN_HASHES[$_h]}
    _src="components/${_label}"
    if [ ! -f "$_src" ]; then
      echo "::error::the AD-35 roster pins '${_label}' but ${_src} does not exist here — the roster no longer describes the shared components (roster drift). Regenerate KNOWN_HASHES in orvex-studio-contracts/.github/workflows/manifest-copy-check.yml."
      fail=1
      continue
    fi
    if [ -z "${SEEN_SOURCE[$_label]:-}" ]; then
      # The hash pass already reports the stale case with the fuller
      # message (it is the one place that knows the file was hashed
      # and mismatched). Reaching here with the file PRESENT and not
      # reported means the hash pass never saw it at all — a tracked
      # gitlink, or a path the enumeration skipped. Either way the
      # roster is describing something this run did not verify, which
      # is exactly the silent hole the owner leg exists to close.
      echo "::error::${_src} exists but was never verified against the roster entry pinned for '${_label}' — the owner leg cannot confirm the roster describes it, so it is not describing anything this run checked (AD-35 roster drift). Regenerate KNOWN_HASHES in orvex-studio-contracts/.github/workflows/manifest-copy-check.yml."
      fail=1
    fi
  done

  # ...and the other direction: a components/** file with no roster
  # entry is simply unprotected — vendoring it anywhere in the family
  # would go unnoticed. A new component, a renamed file and a
  # regenerated-but-unpinned one all land here.
  for _f in "${files[@]}"; do
    case "$_f" in components/*) ;; *) continue ;; esac
    _label=${_f#components/}
    [ -n "${ROSTER_LABELS[$_label]:-}" ] && continue
    echo "::error::${_f} is a shared component file with NO AD-35 roster entry — a repo vendoring it would not be caught. Add its sha256 to KNOWN_HASHES in orvex-studio-contracts/.github/workflows/manifest-copy-check.yml."
    fail=1
  done
fi

# ── The banned mechanism: a CROSS-REPO `components:` reference ──
#
# PO-2026-07-30-1. This is the leg that makes the ruling enforceable
# rather than a note in a changelog, and it is the shape this very
# gate used to PRESCRIBE ("Reference the shared my-idp-apps component
# instead of vendoring its content"). ArgoCD renders a remote
# `components:` entry by SILENTLY DROPPING IT — no error, no
# SyncFailed, no Degraded — so the manifests that reach the cluster
# are missing the ExternalSecrets / cluster-config / telemetry block
# while the Application reads Healthy. Proven live in wave-1. It is
# the worst failure shape this family has: a green dashboard over a
# manifest that was never applied.
#
# Scoped deliberately narrowly, to `components:` in a kustomization
# file and nothing else:
#   * `resources:` may legitimately be remote and is NOT touched;
#   * an ArgoCD AppProject's `sourceRepos:` list is full of
#     `https://github.com/orvexai/...` entries (21 of them in
#     my-idp-apps' own applications/**) and must not be flagged — it
#     is why this scans kustomization files by name rather than
#     grepping every YAML for a URL.
# A top-level `components:` key only means kustomize components in a
# kustomization file, so anchoring at column 0 there is both precise
# and sufficient; a nested `components:` inside a patch body is a
# different key and is skipped.
kfiles=()
for f in "${files[@]}"; do
  case "${f##*/}" in
    kustomization.yaml|kustomization.yml|Kustomization) kfiles+=("$f") ;;
  esac
done
if [ "${#kfiles[@]}" -gt 0 ]; then
  # One awk pass over all of them; `FILENAME`/`FNR` give the report
  # its location. Handles block style (`components:` then `- entry`)
  # and flow style (`components: [a, b]`) because both appear in the
  # wild and only checking one would be a hole an author could walk
  # through without knowing it.
  remote_refs=$(awk '
    function flag(file, line, val) {
      gsub(/^[[:space:]]*["\047]?/, "", val)
      gsub(/["\047]?[[:space:]]*,?[[:space:]]*\]?[[:space:]]*$/, "", val)
      if (val ~ /^(https?|ssh|git):\/\// || val ~ /^git@/ || val ~ /^github\.com\// || val ~ /^[^ ]+\.git(\/|\?|$)/)
        printf "%s:%d:%s\n", file, line, val
    }
    FNR == 1 { inblock = 0 }
    # A top-level key other than `components:` closes the block.
    /^[^[:space:]#]/ && !/^components:/ { inblock = 0 }
    /^components:[[:space:]]*\[/ {
      body = $0; sub(/^components:[[:space:]]*\[/, "", body); sub(/\].*$/, "", body)
      n = split(body, parts, ",")
      for (i = 1; i <= n; i++) flag(FILENAME, FNR, parts[i])
      next
    }
    /^components:[[:space:]]*$/ { inblock = 1; next }
    inblock {
      if ($0 ~ /^[[:space:]]*(#|$)/) next          # comment / blank: block continues
      if ($0 !~ /^[[:space:]]*-[[:space:]]*[^[:space:]]/) { inblock = 0; next }
      item = $0; sub(/^[[:space:]]*-[[:space:]]*/, "", item); sub(/[[:space:]]*#.*$/, "", item)
      flag(FILENAME, FNR, item)
    }
  ' "${kfiles[@]}") || {
    echo "::error::manifest-copy-check could not scan kustomization files for cross-repo component refs; refusing to report a verdict."
    exit 2
  }
  if [ -n "$remote_refs" ]; then
    while IFS= read -r ref; do
      [ -n "$ref" ] || continue
      _loc=${ref%%:*}; _rest=${ref#*:}; _line=${_rest%%:*}; _val=${_rest#*:}
      echo "::error file=${_loc},line=${_line}::cross-repo kustomize \`components:\` reference — BANNED (PO-2026-07-30-1). ArgoCD drops a remote component SILENTLY, so the rendered manifest is missing it while the Application still reads Healthy: ${_val}"
    done <<< "$remote_refs"
    echo "Materialize the component in-repo at <overlay-root>/components/<label> (byte-for-byte from orvexai/my-idp-apps) and reference that local path. This gate keeps the copy in sync."
    fail=1
  fi
fi

if [ "$fail" -ne 0 ]; then exit 1; fi
if [ "$is_owner" -eq 1 ]; then
  echo "OK: the AD-35 roster describes components/** exactly (${#KNOWN_HASHES[@]} entries), no file outside it vendors a shared manifest, and no kustomization references a component cross-repo."
else
  echo "OK: every materialized shared component is in sync with the roster (${#KNOWN_HASHES[@]} entries), no stray byte-copy, and no cross-repo component reference."
fi
