#!/usr/bin/env bash
# Code generated by orvex-studio-contracts gen/go from the declaration plane.
# DO NOT EDIT — regenerate via `go run ./gen/go` (regen-diff gated, Spine AD-5).
#
# substrate-lint-drift, standalone. Byte-identical CHECK to the reusable workflow
# beside it; this variant exists for a PUBLIC consuming repo, which GitHub does
# not permit to call a private repo's reusable workflow (orvex-wiki).
#
# Adoption: commit this file beside the generated config and run it as a CI step
# whose context is REQUIRED. Because the roster then lives in the consuming repo,
# this variant closes a hand-edit of the config but NOT a two-file edit that also
# rewrites the digest here — a private repo should use the reusable workflow,
# where the roster is out of its reach (gates/lint/README.md).
#
# Run from the consuming repo's root. Exit 0 = match, 1 = drift, 2 = cannot rule.
set -uo pipefail

err() {
  if [ "${GITHUB_ACTIONS:-}" = "true" ]; then
    printf '::error::%s\n' "$*"
  else
    printf 'substrate-lint-drift: ERROR: %s\n' "$*" >&2
  fi
}

# The consuming repo's NAME. SUBSTRATE_LINT_REPO overrides it so the check is
# runnable locally and testable; in CI it comes from GITHUB_REPOSITORY.
repo="${SUBSTRATE_LINT_REPO:-}"
if [ -z "$repo" ]; then
  gh_repo="${GITHUB_REPOSITORY:-}"
  repo="${gh_repo##*/}"
fi
if [ -z "$repo" ]; then
  err "cannot determine the consuming repo (neither SUBSTRATE_LINT_REPO nor GITHUB_REPOSITORY is set); refusing to report a verdict."
  exit 2
fi
if ! command -v sha256sum >/dev/null 2>&1; then
  err "sha256sum is not available on this runner; refusing to report a verdict."
  exit 2
fi

# ROSTER — Code generated from the SAME emission pass that produced the configs:
#   <consuming repo> <path relative to that repo's root> <sha256 of the emitted bytes>
roster=$(cat <<'SUBSTRATE_LINT_ROSTER'
orvex-studio-ai .golangci.substrate.yml d404747f7cfe6974b770f2ae1006109da6dd8e31b1a32da61db2bac5c922dbd4
orvex-studio-api eslint.substrate.config.mjs 347dfdcacdc87021c8d0a0d1bddf86f1f050859d5db397fd4017faeb66503798
orvex-studio-audit .golangci.substrate.yml 6d2d8a57045c8212134b3051284fc8adb132252939fb36f96e54598f743ad8e9
orvex-studio-billing .golangci.substrate.yml 81f726c5ca7ae8b8737923516e22d2f9b6305218c4c804394706852d207b8532
orvex-studio-console .golangci.substrate.yml 0eba9edd5e94a8e75ee64f5d23da7343f4474dac316587352d1f37001dc95f94
orvex-studio-console eslint.substrate.config.mjs b5cf2107f694279c99fb4dd32b38eb160cffa1e1516e5746533d7db64a7bf44a
orvex-studio-identity .golangci.substrate.yml 2cddc8beb0e0d6cc7a18706060dc9052da02319aa2abf02eef32dec07abe9ed9
orvex-studio-knowledge .golangci.substrate.yml 1a6b916ad5516aa363de1d6311055a799d9aed610d6c4a3a7da2c5c877096f32
orvex-studio-mcp eslint.substrate.config.mjs f5ea01dcce66f905581a2a8c5aebeb125e1df359a248485cb2efcdc727beba07
orvex-studio-staging .golangci.substrate.yml 5716aa06339da88a7a3e28b23bf0a2053c08b8113507b8c99e8ee0d87f369ea1
orvex-studio-ui eslint.substrate.config.mjs 039957e970bbe79cc76c2085aad6163f57261698ed20f7063520d01a40565997
orvex-wiki eslint.substrate.config.mjs 8882babfbb976146d77971f986e2c4eb0cdcc531a2c0251f08360204c41c31c1
orvex-wiki-api .golangci.substrate.yml 629f88eba0a883a45c7e1210e238528f8e8a21bd1a86460dafb1c3f6fd08574f
orvex-studio-workflows .golangci.substrate.yml 31730487c50bf38e931ec4b00ef8385ba4d82d75acaba51fc096b327179324df
orvex-studio-workgraph .golangci.substrate.yml cefcbad4748be3ef6677c19431a14aef0e7bdc3ffd7540c5f18ad31208ebda05
orvex-cli .golangci.substrate.yml 58dc693f7ca595ffc21c3c8f81baa6e0918014270830d35182bd5e3095099795
orvex-studio-contracts eslint.substrate.config.mjs 1d333b7d7b45920369daab340a91aa91486e968c0f16e2d154c76fa1b292cf6a
orvex-studio-extension eslint.substrate.config.mjs 80461aeaf07207e904c1fd26833e8e64df463eb03007401f2c5d6ce4da1e8b15
orvex-studio-lib .golangci.substrate.yml c3c73327129d55aa9c0c26aa4a2eb6787b5a396e8c5b33b5e8932bfe3a6d696c
SUBSTRATE_LINT_ROSTER
)

matched=0
fail=0
while read -r r f want; do
  [ -n "${r:-}" ] || continue
  [ "$r" = "$repo" ] || continue
  matched=$((matched + 1))
  if [ ! -f "$f" ]; then
    err "$repo is a materialised fleet member but $f is not committed. Copy it from orvex-studio-contracts at the pinned tag (gates/lint/README.md) — do not hand-write it."
    fail=1
    continue
  fi
  got=$(sha256sum -- "$f" | cut -d' ' -f1)
  if [ -z "$got" ]; then
    err "could not hash $f; refusing to report a verdict."
    exit 2
  fi
  if [ "$got" != "$want" ]; then
    err "$f has DRIFTED from the orvex-studio-contracts generator (sha256 $got, expected $want). It is Code-generated: change the ban DATA in contracts and re-copy the regenerated file — never edit this copy."
    fail=1
  fi
done <<SUBSTRATE_LINT_INPUT
$roster
SUBSTRATE_LINT_INPUT

# A repo the roster does not know cannot be ruled on: either it is not a fleet
# member in a materialised language, or this check is pinned to a contracts tag
# older than the member's onboarding. Both are RED, never a silent pass.
if [ "$matched" -eq 0 ]; then
  err "$repo is not in the substrate-lint materialisation roster at this contracts tag; refusing to report a verdict."
  exit 2
fi
if [ "$fail" -ne 0 ]; then exit 1; fi
echo "substrate-lint-drift: OK — $matched Code-generated substrate lint config(s) in $repo are byte-identical to the contracts generator."
