#!/usr/bin/env bash
# Code generated by orvex-studio-contracts gen/go from the declaration plane.
# DO NOT EDIT — regenerate via `go run ./gen/go` (regen-diff gated, Spine AD-5).
#
# substrate-lint-drift, standalone. Byte-identical CHECK to the reusable workflow
# beside it; this variant exists for a PUBLIC consuming repo, which GitHub does
# not permit to call a private repo's reusable workflow (orvex-wiki).
#
# Adoption: commit this file beside the generated config and run it as a CI step
# whose context is REQUIRED. Because the roster then lives in the consuming repo,
# this variant closes a hand-edit of the config but NOT a two-file edit that also
# rewrites the digest here — a private repo should use the reusable workflow,
# where the roster is out of its reach (gates/lint/README.md).
#
# Run from the consuming repo's root. Exit 0 = match, 1 = drift, 2 = cannot rule.
set -uo pipefail

err() {
  if [ "${GITHUB_ACTIONS:-}" = "true" ]; then
    printf '::error::%s\n' "$*"
  else
    printf 'substrate-lint-drift: ERROR: %s\n' "$*" >&2
  fi
}

# The consuming repo's NAME. SUBSTRATE_LINT_REPO overrides it so the check is
# runnable locally and testable; in CI it comes from GITHUB_REPOSITORY.
repo="${SUBSTRATE_LINT_REPO:-}"
if [ -z "$repo" ]; then
  gh_repo="${GITHUB_REPOSITORY:-}"
  repo="${gh_repo##*/}"
fi
if [ -z "$repo" ]; then
  err "cannot determine the consuming repo (neither SUBSTRATE_LINT_REPO nor GITHUB_REPOSITORY is set); refusing to report a verdict."
  exit 2
fi
if ! command -v sha256sum >/dev/null 2>&1; then
  err "sha256sum is not available on this runner; refusing to report a verdict."
  exit 2
fi

# ROSTER — Code generated from the SAME emission pass that produced the configs:
#   <consuming repo> <path relative to that repo's root> <sha256 of the emitted bytes>
roster=$(cat <<'SUBSTRATE_LINT_ROSTER'
orvex-studio-ai .golangci.substrate.yml a7e8f78257a75f80350380b75b1fd1309fdb8f89727356dba25058938b303ae5
orvex-studio-api eslint.substrate.config.mjs c64466d8475f90ba53ff8c974fb7cfc6a2ef42b6e84668f369c66b0a01121315
orvex-studio-audit .golangci.substrate.yml f8502eefbcedc75e5bd9be98f6768065876e17a7665b3a193ed773ac2e51bc9e
orvex-studio-billing .golangci.substrate.yml d9ce394170e6e4de299bcbc95328cde4bd9537e76a19eaad137d5e80c14f4ddd
orvex-studio-console .golangci.substrate.yml 030b93f1be18605e204145d1ab9b39298b5515655600659a029871335232220a
orvex-studio-console eslint.substrate.config.mjs 3a899b235dd39f02807937f191343dd7867b9d6321392ea31605cdf07b18b558
orvex-studio-identity .golangci.substrate.yml 1bd293fc0a1f1553aec1a0b5b561f6c9096ca0521d14b657a8f20088a4e9d604
orvex-studio-knowledge .golangci.substrate.yml cb08afb3a17093c59debf1fb7bcf46b8b1a136ec38b751e186af25c002e63923
orvex-studio-mcp eslint.substrate.config.mjs 4f8ceb3a2d37c9596563a307175149613a91c241f10d103fe8dd06a354a35ac3
orvex-studio-staging .golangci.substrate.yml 58e8f96b8ad975247a729e8a3e3c05b9de974f7680d6089b7bd378704a2d18bb
orvex-studio-ui eslint.substrate.config.mjs 135afc0f25b4729ce95f2482efaaad0bed4ec40031c8b5736da6713e1811bf83
orvex-wiki eslint.substrate.config.mjs 614e361bd3db9f6ffe61ee4e5e91f3520dca22b12705f92f2708080d898ca8d5
orvex-wiki-api .golangci.substrate.yml 567725775b07f9c9c427640385dc71d5386f86d5092d0668af1f4cef14996bb5
orvex-studio-workflows .golangci.substrate.yml 7ef9ec5644d71486e37119373804e2e005821ec2d0cedf2de3d828b36c9f8ed2
orvex-studio-workgraph .golangci.substrate.yml 7e21b2659f6377ddea104554d4a53da3b7b1288409323b45260394c7338f721c
orvex-cli .golangci.substrate.yml 0aa235bb4da40992463edd30ca469850f2620359200393b4b5c6909d5e57fe1a
orvex-studio-contracts eslint.substrate.config.mjs 26bf9c2ad54470c696e2aa233fcbb6dda9ab57a216deb279190234dedaf565a5
orvex-studio-extension eslint.substrate.config.mjs 0d78c4426f469da4f1ee26247c27607c0b2372b5dadbf8c38fd33410f763a615
orvex-studio-lib .golangci.substrate.yml 4e9bf513df88d2ea8bcd7cdd704ac3d0416fc2836d8ebcaae3d31f82af020e2a
SUBSTRATE_LINT_ROSTER
)

matched=0
fail=0
while read -r r f want; do
  [ -n "${r:-}" ] || continue
  [ "$r" = "$repo" ] || continue
  matched=$((matched + 1))
  if [ ! -f "$f" ]; then
    err "$repo is a materialised fleet member but $f is not committed. Copy it from orvex-studio-contracts at the pinned tag (gates/lint/README.md) — do not hand-write it."
    fail=1
    continue
  fi
  got=$(sha256sum -- "$f" | cut -d' ' -f1)
  if [ -z "$got" ]; then
    err "could not hash $f; refusing to report a verdict."
    exit 2
  fi
  if [ "$got" != "$want" ]; then
    err "$f has DRIFTED from the orvex-studio-contracts generator (sha256 $got, expected $want). It is Code-generated: change the ban DATA in contracts and re-copy the regenerated file — never edit this copy."
    fail=1
  fi
done <<SUBSTRATE_LINT_INPUT
$roster
SUBSTRATE_LINT_INPUT

# A repo the roster does not know cannot be ruled on: either it is not a fleet
# member in a materialised language, or this check is pinned to a contracts tag
# older than the member's onboarding. Both are RED, never a silent pass.
if [ "$matched" -eq 0 ]; then
  err "$repo is not in the substrate-lint materialisation roster at this contracts tag; refusing to report a verdict."
  exit 2
fi
if [ "$fail" -ne 0 ]; then exit 1; fi
echo "substrate-lint-drift: OK — $matched Code-generated substrate lint config(s) in $repo are byte-identical to the contracts generator."
