// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) Orvex, Inc. — part of the orvex-wiki AGPL engine (CS §13).
// See the LICENSE file at the repository root for the full license text.

import { webcrypto } from 'node:crypto';

import { createLocalEs256Jwks, narrowEdgeJwks } from './local-es256-jwks';
import type { EdgeJwks } from './local-es256-jwks';

/**
 * createLocalEs256Jwks (ENG-3495) — the from-scratch replacement for `jose`'s
 * `createLocalJWKSet`, which `edge-assertion-key-source.ts` and
 * `remote-edge-assertion-key-source.ts` were the last two importers of in
 * `apps/server/src`.
 *
 * These cases pin the selection/failure semantics the previous implementation
 * gave for free and that both key sources' `resolve()` contracts depend on —
 * every "no usable key" outcome collapses to `undefined`, nothing throws — plus
 * the one thing a lookup table can silently get wrong: whether the CryptoKey it
 * hands back actually verifies a real ES256 signature. That last case is the
 * load-bearing one; a resolver that returned a plausible-but-wrong key would
 * pass every `toBeDefined()` and fail only in production.
 *
 * Keys are generated by Node's Web Crypto, never hand-authored (CS §5).
 */

async function generateEs256(): Promise<webcrypto.CryptoKeyPair> {
  return (await webcrypto.subtle.generateKey(
    { name: 'ECDSA', namedCurve: 'P-256' },
    true,
    ['sign', 'verify'],
  )) as webcrypto.CryptoKeyPair;
}

/** Export a public key as a JWKS entry shaped like identity's real ones. */
async function publicJwk(
  pair: webcrypto.CryptoKeyPair,
  overrides: Record<string, unknown> = {},
): Promise<Record<string, unknown>> {
  const jwk = await webcrypto.subtle.exportKey('jwk', pair.publicKey);
  delete jwk.key_ops;
  delete jwk.ext;
  return { ...jwk, kid: 'kid-a', alg: 'ES256', use: 'sig', ...overrides };
}

describe('createLocalEs256Jwks (ENG-3495)', () => {
  it('resolves a kid to a CryptoKey that VERIFIES a real ES256 signature the matching private key produced', async () => {
    const pair = await generateEs256();
    const jwks: EdgeJwks = { keys: [await publicJwk(pair)] };

    const key = await createLocalEs256Jwks(jwks)('kid-a');
    expect(key).toBeDefined();

    const message = new TextEncoder().encode('edge-assertion.signing.input');
    const signature = await webcrypto.subtle.sign(
      { name: 'ECDSA', hash: 'SHA-256' },
      pair.privateKey,
      message,
    );
    await expect(
      webcrypto.subtle.verify(
        { name: 'ECDSA', hash: 'SHA-256' },
        key as webcrypto.CryptoKey,
        signature,
        message,
      ),
    ).resolves.toBe(true);
  });

  it('the resolved key REJECTS a signature from a DIFFERENT keypair (the lookup returns the right key, not just any key)', async () => {
    const mine = await generateEs256();
    const other = await generateEs256();
    const jwks: EdgeJwks = { keys: [await publicJwk(mine)] };

    const key = await createLocalEs256Jwks(jwks)('kid-a');
    const message = new TextEncoder().encode('edge-assertion.signing.input');
    const foreign = await webcrypto.subtle.sign(
      { name: 'ECDSA', hash: 'SHA-256' },
      other.privateKey,
      message,
    );
    await expect(
      webcrypto.subtle.verify(
        { name: 'ECDSA', hash: 'SHA-256' },
        key as webcrypto.CryptoKey,
        foreign,
        message,
      ),
    ).resolves.toBe(false);
  });

  it('the resolved key is verify-only and non-extractable (a verification key source can never be used to sign or to leak material)', async () => {
    const pair = await generateEs256();
    const key = (await createLocalEs256Jwks({
      keys: [await publicJwk(pair)],
    })('kid-a')) as webcrypto.CryptoKey;

    expect(key.usages).toEqual(['verify']);
    expect(key.extractable).toBe(false);
    // WebCrypto raises a DOMException (InvalidAccessError) here, not an Error
    // subclass — assert the rejection itself, not its constructor.
    await expect(webcrypto.subtle.exportKey('jwk', key)).rejects.toBeDefined();
  });

  it('memoizes the import: the SAME CryptoKey instance comes back for repeat resolves, including concurrent first-resolves', async () => {
    const pair = await generateEs256();
    const resolve = createLocalEs256Jwks({ keys: [await publicJwk(pair)] });

    const [a, b] = await Promise.all([resolve('kid-a'), resolve('kid-a')]);
    expect(a).toBe(b);
    expect(await resolve('kid-a')).toBe(a);
  });

  describe('returns undefined (never throws) for every "no usable key" outcome', () => {
    it('an absent kid', async () => {
      const pair = await generateEs256();
      const resolve = createLocalEs256Jwks({ keys: [await publicJwk(pair)] });
      await expect(resolve('kid-nope')).resolves.toBeUndefined();
    });

    it('an AMBIGUOUS kid — two keys share it, so which one signed is unknown and the guard denies rather than guessing', async () => {
      const first = await generateEs256();
      const second = await generateEs256();
      const resolve = createLocalEs256Jwks({
        keys: [await publicJwk(first), await publicJwk(second)],
      });
      await expect(resolve('kid-a')).resolves.toBeUndefined();
    });

    it('a key declared for encryption (use: "enc")', async () => {
      const pair = await generateEs256();
      const resolve = createLocalEs256Jwks({
        keys: [await publicJwk(pair, { use: 'enc' })],
      });
      await expect(resolve('kid-a')).resolves.toBeUndefined();
    });

    it('a key declaring a non-ES256 alg', async () => {
      const pair = await generateEs256();
      const resolve = createLocalEs256Jwks({
        keys: [await publicJwk(pair, { alg: 'ES384' })],
      });
      await expect(resolve('kid-a')).resolves.toBeUndefined();
    });

    it('a key on the wrong curve (P-384 is not ES256)', async () => {
      const pair = (await webcrypto.subtle.generateKey(
        { name: 'ECDSA', namedCurve: 'P-384' },
        true,
        ['sign', 'verify'],
      )) as webcrypto.CryptoKeyPair;
      const jwk = await webcrypto.subtle.exportKey('jwk', pair.publicKey);
      delete jwk.key_ops;
      delete jwk.ext;
      const resolve = createLocalEs256Jwks({
        keys: [{ ...jwk, kid: 'kid-a', use: 'sig' }],
      });
      await expect(resolve('kid-a')).resolves.toBeUndefined();
    });

    it('a non-EC key type (RSA)', async () => {
      const resolve = createLocalEs256Jwks({
        keys: [{ kty: 'RSA', kid: 'kid-a', alg: 'RS256', n: 'x', e: 'AQAB' }],
      });
      await expect(resolve('kid-a')).resolves.toBeUndefined();
    });

    it('a structurally EC/P-256 entry whose key MATERIAL is unusable — importKey rejects and that is folded to undefined, not thrown', async () => {
      const resolve = createLocalEs256Jwks({
        keys: [
          { kty: 'EC', crv: 'P-256', kid: 'kid-a', alg: 'ES256', use: 'sig' },
        ],
      });
      await expect(resolve('kid-a')).resolves.toBeUndefined();
    });

    it('junk entries in the key array — a null/string/number never crashes selection', async () => {
      const pair = await generateEs256();
      const resolve = createLocalEs256Jwks({
        keys: [null, 'nonsense', 42, await publicJwk(pair)],
      });
      await expect(resolve('kid-a')).resolves.toBeDefined();
      await expect(resolve('kid-b')).resolves.toBeUndefined();
    });

    it('an entry with no kid at all', async () => {
      const pair = await generateEs256();
      const resolve = createLocalEs256Jwks({
        keys: [await publicJwk(pair, { kid: undefined })],
      });
      await expect(resolve('kid-a')).resolves.toBeUndefined();
    });
  });

  describe('narrowEdgeJwks — a malformed key set is unusable, never an empty accept', () => {
    it.each([
      ['a non-object', 'not-a-jwks'],
      ['null', null],
      ['an object with no keys', {}],
      ['keys that is not an array', { keys: 'nope' }],
      ['an EMPTY keys array', { keys: [] }],
    ])('throws on %s', (_label, payload) => {
      expect(() => narrowEdgeJwks(payload)).toThrow();
    });

    it('accepts a well-formed set', () => {
      expect(narrowEdgeJwks({ keys: [{ kty: 'EC' }] })).toEqual({
        keys: [{ kty: 'EC' }],
      });
    });
  });
});
