import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * ENG-2479 T5 — `TestDbTypesMatchV095StockPlusDeclarationMergeFile` (AC3).
 *
 * Per the ticket's own "what NOT to test" guidance: never snapshot/hash
 * `db.d.ts` byte-for-byte (that breaks on every legitimate future
 * `kysely-codegen` regeneration). Instead assert the SPECIFIC fields AC3
 * names as "restored" (the SCIM EE columns + `is_base`/`base_schema_version`
 * — proof nothing silently stripped them from the stock v0.95 shape) and
 * the declaration-merge-file BOUNDARY: `db.interface.ts` is the one file
 * that extends the generated `DB` type with additive interfaces, and those
 * additive interfaces (`PageEmbeddings`) do NOT ALSO live inline inside
 * `db.d.ts` (which would mean two competing, driftable sources of truth for
 * the same table).
 */
describe('DbTypesVerbatimSpec', () => {
  const typesDir = join(__dirname, '../../types');
  const dbDts = readFileSync(join(typesDir, 'db.d.ts'), 'utf8');
  const dbInterfaceTs = readFileSync(
    join(typesDir, 'db.interface.ts'),
    'utf8',
  );

  it('carries the header marking db.d.ts as codegen-owned (never hand-edited)', () => {
    expect(dbDts).toMatch(/generated by kysely-codegen/i);
    expect(dbDts).toMatch(/do not edit it manually/i);
  });

  it('restores the SCIM EE columns v0.95 stock schema carries', () => {
    // Users.scimExternalId
    expect(dbDts).toMatch(/scimExternalId:\s*string \| null/);
    // Workspaces.isScimEnabled
    expect(dbDts).toMatch(/isScimEnabled:\s*Generated<boolean>/);
    // The scim_tokens table's generated type
    expect(dbDts).toMatch(/export interface ScimTokens\b/);
    expect(dbDts).toMatch(/scimTokens:\s*ScimTokens;/);
  });

  it('restores is_base / base_schema_version on Pages', () => {
    expect(dbDts).toMatch(/isBase:\s*Generated<boolean>/);
    expect(dbDts).toMatch(/baseSchemaVersion:\s*Generated<number>/);
  });

  it('routes additive, non-introspectable types through db.interface.ts only, not inline in db.d.ts', () => {
    // db.interface.ts is the declaration-merge file: it imports the
    // generated `DB` and extends it.
    expect(dbInterfaceTs).toMatch(
      /import\s*{\s*DB\s*}\s*from\s*['"]@docmost\/db\/types\/db['"]/,
    );
    expect(dbInterfaceTs).toMatch(/export interface DbInterface extends DB/);
    expect(dbInterfaceTs).toMatch(/pageEmbeddings:\s*PageEmbeddings/);

    // The merge-only type must NOT also be natively declared inside
    // db.d.ts — if it were, there'd be two sources of truth for the same
    // table and the "additive columns route through one declaration-merge
    // file" boundary AC3 requires would be broken.
    expect(dbDts).not.toMatch(/export interface PageEmbeddings\b/);
    expect(dbDts).not.toMatch(/pageEmbeddings:/);
  });
});
