// Code generated by scripts/generate-audit-events.mjs from the pinned
// orvex-studio-contracts audit declaration — DO NOT EDIT (AD-5: generated,
// never transcribed; the regen-diff gate reds on drift).
// Pin: orvexai/orvex-studio-contracts@950d25daa8d32456bfa61bd1939078b690bb081a (ticket/ENG-3167)
// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) Orvex, Inc. — part of the orvex-wiki AGPL engine (CS §13).

/** The engine's AD-31 service token — the CloudEvents `source` of every
 *  audit emission (AD-23: exactly the token, no scheme prefix, no path
 *  suffix, no alias). */
export const AUDIT_EVENT_SOURCE = "orvex-wiki" as const;

/** The contracts-registered `audit.<category>.<verb>` type for every one of
 *  the engine's audit actions (publisher orvex-wiki; AD-23
 *  register-before-emit). Constant NAMES are the engine emit surface;
 *  VALUES are generated contract data. */
export const AuditEvent = {
  WORKSPACE_CREATED: "audit.admin.workspace-created",
  WORKSPACE_UPDATED: "audit.config.workspace-updated",
  WORKSPACE_INVITE_CREATED: "audit.admin.workspace-invite-created",
  WORKSPACE_INVITE_RESENT: "audit.admin.workspace-invite-resent",
  WORKSPACE_INVITE_REVOKED: "audit.admin.workspace-invite-revoked",
  USER_CREATED: "audit.admin.user-created",
  USER_DELETED: "audit.admin.user-deleted",
  USER_LOGIN: "audit.auth.user-login",
  USER_LOGOUT: "audit.auth.user-logout",
  USER_ROLE_CHANGED: "audit.admin.user-role-changed",
  USER_PASSWORD_CHANGED: "audit.auth.user-password-changed",
  USER_PASSWORD_RESET: "audit.auth.user-password-reset",
  USER_UPDATED: "audit.admin.user-updated",
  USER_DEACTIVATED: "audit.admin.user-deactivated",
  USER_ACTIVATED: "audit.admin.user-activated",
  API_KEY_CREATED: "audit.auth.api-key-created",
  API_KEY_UPDATED: "audit.auth.api-key-updated",
  API_KEY_DELETED: "audit.auth.api-key-deleted",
  API_KEY_REVOKED: "audit.auth.api-key-revoked",
  AUTH_FAILED: "audit.auth.auth-failed",
  SCIM_TOKEN_CREATED: "audit.auth.scim-token-created",
  SCIM_TOKEN_UPDATED: "audit.auth.scim-token-updated",
  SCIM_TOKEN_DELETED: "audit.auth.scim-token-deleted",
  SPACE_CREATED: "audit.admin.space-created",
  SPACE_UPDATED: "audit.admin.space-updated",
  SPACE_DELETED: "audit.admin.space-deleted",
  SPACE_MEMBER_ADDED: "audit.admin.space-member-added",
  SPACE_MEMBER_REMOVED: "audit.admin.space-member-removed",
  SPACE_MEMBER_ROLE_CHANGED: "audit.admin.space-member-role-changed",
  GROUP_CREATED: "audit.admin.group-created",
  GROUP_UPDATED: "audit.admin.group-updated",
  GROUP_DELETED: "audit.admin.group-deleted",
  GROUP_MEMBER_ADDED: "audit.admin.group-member-added",
  GROUP_MEMBER_REMOVED: "audit.admin.group-member-removed",
  COMMENT_CREATED: "audit.data-access.comment-created",
  COMMENT_DELETED: "audit.data-access.comment-deleted",
  COMMENT_UPDATED: "audit.data-access.comment-updated",
  COMMENT_RESOLVED: "audit.data-access.comment-resolved",
  COMMENT_REOPENED: "audit.data-access.comment-reopened",
  PAGE_CREATED: "audit.data-access.page-created",
  PAGE_TRASHED: "audit.retention.page-trashed",
  PAGE_DELETED: "audit.retention.page-deleted",
  PAGE_RESTORED: "audit.retention.page-restored",
  PAGE_HISTORY_RESTORED: "audit.data-access.page-history-restored",
  PAGE_MOVED_TO_SPACE: "audit.data-access.page-moved-to-space",
  PAGE_DUPLICATED: "audit.data-access.page-duplicated",
  PAGE_RESTRICTED: "audit.admin.page-restricted",
  PAGE_RESTRICTION_REMOVED: "audit.admin.page-restriction-removed",
  PAGE_PERMISSION_ADDED: "audit.admin.page-permission-added",
  PAGE_PERMISSION_REMOVED: "audit.admin.page-permission-removed",
  PAGE_PERMISSION_ROLE_UPDATED: "audit.admin.page-permission-role-updated",
  PAGE_VERIFICATION_CREATED: "audit.data-access.page-verification-created",
  PAGE_VERIFICATION_UPDATED: "audit.data-access.page-verification-updated",
  PAGE_VERIFICATION_REMOVED: "audit.data-access.page-verification-removed",
  PAGE_VERIFIED: "audit.data-access.page-verified",
  PAGE_APPROVAL_REQUESTED: "audit.consent.page-approval-requested",
  PAGE_APPROVAL_REJECTED: "audit.consent.page-approval-rejected",
  PAGE_MARKED_OBSOLETE: "audit.data-access.page-marked-obsolete",
  PAGE_PROVENANCE_CHANGED: "audit.data-access.page-provenance-changed",
  SHARE_CREATED: "audit.data-access.share-created",
  SHARE_DELETED: "audit.data-access.share-deleted",
  PAGE_IMPORTED: "audit.data-access.page-imported",
  PAGE_EXPORTED: "audit.export.page-exported",
  SPACE_EXPORTED: "audit.export.space-exported",
  SSO_PROVIDER_CREATED: "audit.config.sso-provider-created",
  SSO_PROVIDER_UPDATED: "audit.config.sso-provider-updated",
  SSO_PROVIDER_DELETED: "audit.config.sso-provider-deleted",
  USER_MFA_ENABLED: "audit.auth.user-mfa-enabled",
  USER_MFA_DISABLED: "audit.auth.user-mfa-disabled",
  USER_MFA_BACKUP_CODE_GENERATED: "audit.auth.user-mfa-backup-code-generated",
  LICENSE_ACTIVATED: "audit.admin.license-activated",
  LICENSE_REMOVED: "audit.admin.license-removed",
  ATTACHMENT_UPLOADED: "audit.data-access.attachment-uploaded",
  OIDC_LOGIN_BLOCKED_BY_ENFORCE_SSO: "audit.auth.oidc-login-blocked-by-enforce-sso",
  OIDC_ENFORCE_SSO_TOGGLED: "audit.config.oidc-enforce-sso-toggled",
  RATIFY_GATE_SETTING_UPDATED: "audit.config.ratify-gate-setting-updated",
  RATIFY_GATE_FORCE_SELF_RATIFY: "audit.consent.ratify-gate-force-self-ratify",
  PAGE_SUPERSEDED: "audit.data-access.page-superseded",
  PAGE_UNSUPERSEDED: "audit.data-access.page-unsuperseded",
  SUPERSEDE_FORCED_BYPASS: "audit.admin.page-supersede-forced-bypass",
  FORCE_SUPERSEDE_SETTING_UPDATED: "audit.config.force-supersede-setting-updated",
  TRANSCLUSION_REFERENCE_UNSYNCED: "audit.data-access.transclusion-reference-unsynced",
  TRANSCLUSION_FORCE_DELETE: "audit.data-access.transclusion-force-delete",
} as const;

export type AuditEventType = (typeof AuditEvent)[keyof typeof AuditEvent];

/** Every pinned engine audit type, in pin order — includes types registered
 *  ahead of an engine constant (AD-23 permits register-before-emit). */
export const ALL_WIKI_AUDIT_TYPES = [
  "audit.admin.group-created",
  "audit.admin.group-deleted",
  "audit.admin.group-member-added",
  "audit.admin.group-member-removed",
  "audit.admin.group-updated",
  "audit.admin.license-activated",
  "audit.admin.license-removed",
  "audit.admin.page-permission-added",
  "audit.admin.page-permission-removed",
  "audit.admin.page-permission-role-updated",
  "audit.admin.page-restricted",
  "audit.admin.page-restriction-removed",
  "audit.admin.page-supersede-forced-bypass",
  "audit.admin.space-created",
  "audit.admin.space-deleted",
  "audit.admin.space-member-added",
  "audit.admin.space-member-removed",
  "audit.admin.space-member-role-changed",
  "audit.admin.space-updated",
  "audit.admin.user-activated",
  "audit.admin.user-created",
  "audit.admin.user-deactivated",
  "audit.admin.user-deleted",
  "audit.admin.user-role-changed",
  "audit.admin.user-updated",
  "audit.admin.workspace-created",
  "audit.admin.workspace-invite-created",
  "audit.admin.workspace-invite-resent",
  "audit.admin.workspace-invite-revoked",
  "audit.auth.api-key-created",
  "audit.auth.api-key-deleted",
  "audit.auth.api-key-revoked",
  "audit.auth.api-key-updated",
  "audit.auth.auth-failed",
  "audit.auth.oidc-login-blocked-by-enforce-sso",
  "audit.auth.scim-token-created",
  "audit.auth.scim-token-deleted",
  "audit.auth.scim-token-updated",
  "audit.auth.user-login",
  "audit.auth.user-logout",
  "audit.auth.user-mfa-backup-code-generated",
  "audit.auth.user-mfa-disabled",
  "audit.auth.user-mfa-enabled",
  "audit.auth.user-password-changed",
  "audit.auth.user-password-reset",
  "audit.config.force-supersede-setting-updated",
  "audit.config.oidc-enforce-sso-toggled",
  "audit.config.ratify-gate-setting-updated",
  "audit.config.sso-provider-created",
  "audit.config.sso-provider-deleted",
  "audit.config.sso-provider-updated",
  "audit.config.workspace-updated",
  "audit.consent.page-approval-rejected",
  "audit.consent.page-approval-requested",
  "audit.consent.ratify-gate-force-self-ratify",
  "audit.data-access.attachment-deleted",
  "audit.data-access.attachment-uploaded",
  "audit.data-access.comment-created",
  "audit.data-access.comment-deleted",
  "audit.data-access.comment-reopened",
  "audit.data-access.comment-resolved",
  "audit.data-access.comment-updated",
  "audit.data-access.page-created",
  "audit.data-access.page-duplicated",
  "audit.data-access.page-history-restored",
  "audit.data-access.page-imported",
  "audit.data-access.page-marked-obsolete",
  "audit.data-access.page-moved-to-space",
  "audit.data-access.page-provenance-changed",
  "audit.data-access.page-superseded",
  "audit.data-access.page-unsuperseded",
  "audit.data-access.page-verification-created",
  "audit.data-access.page-verification-removed",
  "audit.data-access.page-verification-updated",
  "audit.data-access.page-verified",
  "audit.data-access.share-created",
  "audit.data-access.share-deleted",
  "audit.data-access.transclusion-force-delete",
  "audit.data-access.transclusion-reference-unsynced",
  "audit.export.page-exported",
  "audit.export.space-exported",
  "audit.retention.page-deleted",
  "audit.retention.page-restored",
  "audit.retention.page-trashed",
] as const;

/** The CLOSED payload field contract per type, from each type's registered
 *  events/schemas/<type>.json (additionalProperties:false — AD-39
 *  references-not-content). The writer builds and VALIDATES every staged
 *  payload against this generated data: required ⊆ keys ⊆ properties, or a
 *  loud typed error (AD-3) — schema drift can never emit silently. */
export const WIKI_AUDIT_PAYLOAD_CONTRACT: Readonly<
  Record<string, { required: readonly string[]; properties: readonly string[] }>
> = {
  "audit.admin.group-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.group-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.group-member-added": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.group-member-removed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.group-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.license-activated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.license-removed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.page-permission-added": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.page-permission-removed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.page-permission-role-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.page-restricted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.page-restriction-removed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.page-supersede-forced-bypass": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.space-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.space-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.space-member-added": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.space-member-removed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.space-member-role-changed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.space-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.user-activated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.user-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.user-deactivated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.user-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.user-role-changed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.user-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.workspace-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.workspace-invite-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.workspace-invite-resent": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.admin.workspace-invite-revoked": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.api-key-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.api-key-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.api-key-revoked": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.api-key-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.auth-failed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.oidc-login-blocked-by-enforce-sso": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.scim-token-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.scim-token-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.scim-token-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.user-login": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.user-logout": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.user-mfa-backup-code-generated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.user-mfa-disabled": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.user-mfa-enabled": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.user-password-changed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.auth.user-password-reset": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.config.force-supersede-setting-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.config.oidc-enforce-sso-toggled": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.config.ratify-gate-setting-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.config.sso-provider-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.config.sso-provider-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.config.sso-provider-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.config.workspace-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.consent.page-approval-rejected": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.consent.page-approval-requested": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.consent.ratify-gate-force-self-ratify": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.attachment-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.attachment-uploaded": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.comment-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.comment-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.comment-reopened": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.comment-resolved": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.comment-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-duplicated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-history-restored": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-imported": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-marked-obsolete": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-moved-to-space": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-provenance-changed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-superseded": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-unsuperseded": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-verification-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-verification-removed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-verification-updated": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.page-verified": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.share-created": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.share-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.transclusion-force-delete": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.data-access.transclusion-reference-unsynced": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.export.page-exported": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.export.space-exported": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.retention.page-deleted": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.retention.page-restored": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
  "audit.retention.page-trashed": {
    required: ["action","actor","occurredAt","outcome"],
    properties: ["action","actor","occurredAt","outcome","resourceId"],
  },
};

// Registered ahead of an engine constant (no live emit site yet):
//   audit.data-access.attachment-deleted
