#!/usr/bin/env bash
# dev-secrets.sh — generate .env.dev for the local prod-parity env (Foundation M2).
#
# Fallback chain (per the foundation prompt's secrets-fetch doctrine):
#   1. --from-cluster : pull the DEPLOYED credentials via kubectl. Only
#      meaningful for a seat that can actually reach the cluster engines
#      (in-cluster execution model); the DSNs it yields point at
#      cluster-local service hosts, not this machine's compose stack.
#   2. default        : generate strong per-machine credentials (openssl) for
#      the local compose stack in docker-compose.dev.yml.
#
# .env.dev is gitignored; nothing here is ever committed. Existing files are
# never overwritten unless --rotate is passed.
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".env.dev"
MODE="local"
ROTATE=0
for arg in "$@"; do
  case "$arg" in
    --from-cluster) MODE="cluster" ;;
    --rotate) ROTATE=1 ;;
    *) echo "usage: $0 [--from-cluster] [--rotate]" >&2; exit 2 ;;
  esac
done

if [[ -f "$ENV_FILE" && "$ROTATE" -ne 1 ]]; then
  echo "$ENV_FILE already exists (use --rotate to regenerate). Nothing done."
  exit 0
fi

rand() { openssl rand -hex "$1"; }

if [[ "$MODE" == "cluster" ]]; then
  # In-cluster seat: read the ESO-synced secrets the deployed engine uses.
  echo "Pulling deployed credentials from namespace orvex-wiki via kubectl..."
  DATABASE_URL=$(kubectl -n orvex-wiki get secret orvex-wiki-db-credentials \
    -o jsonpath='{.data.DATABASE_URL}' | base64 -d)
  REDIS_URL=$(kubectl -n orvex-wiki get secret orvex-wiki-redis-credentials \
    -o jsonpath='{.data.REDIS_URL}' | base64 -d)
  APP_SECRET=$(kubectl -n orvex-wiki get secret orvex-wiki-app-secret \
    -o jsonpath='{.data.APP_SECRET}' | base64 -d)
  AWS_S3_ACCESS_KEY_ID=$(kubectl -n orvex-wiki get secret orvex-wiki-s3-bucket \
    -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
  AWS_S3_SECRET_ACCESS_KEY=$(kubectl -n orvex-wiki get secret orvex-wiki-s3-bucket \
    -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)
  AWS_S3_BUCKET=$(kubectl -n orvex-wiki get configmap orvex-wiki-s3-bucket \
    -o jsonpath='{.data.BUCKET_NAME}')
  AWS_S3_ENDPOINT="http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local"
  DEV_POSTGRES_PASSWORD=""; DEV_REDIS_PASSWORD=""
  DEV_MINIO_ROOT_USER=""; DEV_MINIO_ROOT_PASSWORD=""
else
  DEV_POSTGRES_PASSWORD=$(rand 24)
  DEV_REDIS_PASSWORD=$(rand 24)
  DEV_MINIO_ROOT_USER="orvexdev"
  DEV_MINIO_ROOT_PASSWORD=$(rand 24)
  APP_SECRET=$(rand 32)
  DATABASE_URL="postgresql://orvex-wiki:${DEV_POSTGRES_PASSWORD}@localhost:55432/orvex-wiki"
  REDIS_URL="redis://:${DEV_REDIS_PASSWORD}@localhost:56379"
  AWS_S3_ACCESS_KEY_ID="$DEV_MINIO_ROOT_USER"
  AWS_S3_SECRET_ACCESS_KEY="$DEV_MINIO_ROOT_PASSWORD"
  AWS_S3_BUCKET="orvex-wiki-bucket"
  AWS_S3_ENDPOINT="http://localhost:59000"
fi

umask 177
cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev-secrets.sh ($(date -u +%FT%TZ), mode=$MODE).
# NEVER COMMIT. Consumed by: make env-up / db-migrate / run-local / smoke-test.

# --- compose-level credentials (docker-compose.dev.yml) ---
DEV_POSTGRES_PASSWORD=$DEV_POSTGRES_PASSWORD
DEV_REDIS_PASSWORD=$DEV_REDIS_PASSWORD
DEV_MINIO_ROOT_USER=$DEV_MINIO_ROOT_USER
DEV_MINIO_ROOT_PASSWORD=$DEV_MINIO_ROOT_PASSWORD

# --- engine app env (prod-parity: NODE_ENV=production => boot auto-migrate,
#     STORAGE_DRIVER=s3 like the deployed configmap-env.yaml) ---
NODE_ENV=production
APP_URL=http://localhost:3000
PORT=3000
APP_SECRET=$APP_SECRET
DATABASE_URL=$DATABASE_URL
REDIS_URL=$REDIS_URL
STORAGE_DRIVER=s3
AWS_S3_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY_ID
AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY
AWS_S3_REGION=us-east-1
AWS_S3_BUCKET=$AWS_S3_BUCKET
AWS_S3_ENDPOINT=$AWS_S3_ENDPOINT
AWS_S3_FORCE_PATH_STYLE=true
EOF
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE (mode=$MODE). Run 'make env-info' to see endpoints."
