#!/usr/bin/env bash
#
# orvex-marker-check.sh — keep the greppable 501 sentinel set in lockstep with
# the contract (contracts/openapi.yaml).
#
# The ALL-REAL / no-op != mock doctrine requires that every noop-501 operation's
# handler carries EXACTLY ONE marker-comment line:
#
#     // ORVEX_NOT_IMPLEMENTED: <operationId>
#
# immediately above its throw. This script fails (non-zero) if:
#   * the number of marker-comment lines != the number of noop-501 operations
#     declared in the contract, OR
#   * any noop-501 operationId is missing (or has a duplicate) marker comment, OR
#   * the contract's `real` classification set drifts from the committed real-set.
#
# It is dependency-light: contract parsing prefers python3 + PyYAML; the
# committed real-set line is the fallback cross-check.
#
# Usage:
#   scripts/orvex-marker-check.sh              # verify (default; the CI gate)
#   scripts/orvex-marker-check.sh --checklist  # regenerate docs/delivery-checklist.md, then verify
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="$REPO_ROOT/apps/server/src"
SPEC="$REPO_ROOT/contracts/openapi.yaml"
CHECKLIST="$REPO_ROOT/docs/delivery-checklist.md"
MARKER='ORVEX_NOT_IMPLEMENTED: '

# The deliberate REAL operations, committed here as the dependency-light
# cross-check against the contract's `x-classification: real` set (comma-joined
# in contract path order): the FR-W6 session-mint (`orvexSessionExchange`, wired
# to the real introspect→resolve→mint path), the FR-W19 written-source offer
# (`orvexSourceOffer`), and the ENG-1578 registry cross-cell tenant-MOVE
# (`orvexTenantCellMove`, wired to identity's real `Registry.Move` — distinct
# from the still-501 A-MOVE quiesce/export/import/activate bulk-content steps).
REAL_SET_COMMITTED="orvexSessionExchange,orvexSourceOffer,orvexTenantCellMove"

MODE="${1:-check}"

[[ -f "$SPEC" ]] || { echo "FAIL: contract not found: $SPEC" >&2; exit 2; }
command -v python3 >/dev/null 2>&1 || { echo "FAIL: python3 required" >&2; exit 2; }

count_nonempty() { awk 'NF{c++} END{print c+0}' <<<"${1:-}"; }

# ── contract side: TSV of  operationId \t classification \t anchor \t summary ──
OPS_TSV="$(
python3 - "$SPEC" <<'PY'
import sys, re, yaml
spec = yaml.safe_load(open(sys.argv[1]))
for path, item in (spec.get('paths') or {}).items():
    if not isinstance(item, dict):
        continue
    for method, op in item.items():
        if not isinstance(op, dict):
            continue
        opid = op.get('operationId')
        if not opid:
            continue
        cls = op.get('x-classification', '') or ''
        desc = op.get('description', '') or ''
        m = re.search(r'FR-W\d+|A-[A-Z]{2,}', desc)
        anchor = m.group(0) if m else '-'
        summary = (op.get('summary', '') or '').replace('\t', ' ').strip()
        print(f"{opid}\t{cls}\t{anchor}\t{summary}")
PY
)"

NOOP_IDS="$(awk -F'\t' '$2=="noop-501"{print $1}' <<<"$OPS_TSV")"
REAL_IDS="$(awk -F'\t' '$2=="real"{print $1}' <<<"$OPS_TSV")"

NOOP_COUNT="$(count_nonempty "$NOOP_IDS")"
REAL_COUNT="$(count_nonempty "$REAL_IDS")"

# ── code side: marker-comment count ──
MARKER_COUNT="$( { grep -r "$MARKER" "$SRC_DIR" --include='*.ts' || true; } | wc -l | tr -d ' ')"

# ── optionally (re)generate the delivery checklist FROM the parsed set ──
if [[ "$MODE" == "--checklist" ]]; then
  mkdir -p "$(dirname "$CHECKLIST")"
  {
    echo "<!-- GENERATED by scripts/orvex-marker-check.sh --checklist — do NOT hand-edit; regenerate. -->"
    echo "# Orvex primitive — delivery checklist"
    echo
    echo "One checkbox per NOT_IMPLEMENTED (noop-501) operation in \`contracts/openapi.yaml\`."
    echo "Each box is a typed 501 sentinel today (the typed contract is day-1); delivery fills"
    echo "in the LOGIC. Regenerate with \`scripts/orvex-marker-check.sh --checklist\` — never hand-edit."
    echo
    echo "## Not-yet-wired operations (noop-501)"
    echo
    while IFS=$'\t' read -r opid cls anchor summary; do
      [[ "$cls" == "noop-501" ]] || continue
      echo "- [ ] \`$opid\` — $anchor — $summary"
    done <<<"$OPS_TSV"
    echo
    echo "## Real from day one (no 501)"
    echo
    while IFS=$'\t' read -r opid cls anchor summary; do
      [[ "$cls" == "real" ]] || continue
      echo "- [x] \`$opid\` — $anchor — $summary"
    done <<<"$OPS_TSV"
  } >"$CHECKLIST"
  echo "regenerated: $CHECKLIST"
fi

# ── report ──
echo "contract noop-501 operations : $NOOP_COUNT"
echo "code marker-comment lines    : $MARKER_COUNT"
echo "contract real operations     : $REAL_COUNT ($(tr '\n' ' ' <<<"$REAL_IDS" | sed 's/ *$//'))"

fail=0

if [[ "$MARKER_COUNT" != "$NOOP_COUNT" ]]; then
  echo "FAIL: marker-comment count ($MARKER_COUNT) != contract noop-501 count ($NOOP_COUNT)" >&2
  fail=1
fi

# Each noop-501 operationId must have EXACTLY ONE marker comment.
while IFS= read -r opid; do
  [[ -z "$opid" ]] && continue
  n="$( { grep -rF "${MARKER}${opid}" "$SRC_DIR" --include='*.ts' || true; } | wc -l | tr -d ' ')"
  if [[ "$n" != "1" ]]; then
    echo "FAIL: operationId '$opid' has $n marker comments (expected exactly 1)" >&2
    fail=1
  fi
done <<<"$NOOP_IDS"

# The contract's `real` set must match the committed real-set (drift guard).
REAL_JOINED="$(tr '\n' ',' <<<"$REAL_IDS" | sed 's/,$//')"
if [[ "$REAL_JOINED" != "$REAL_SET_COMMITTED" ]]; then
  echo "FAIL: contract real-set '$REAL_JOINED' != committed real-set '$REAL_SET_COMMITTED'" >&2
  fail=1
fi

if [[ "$fail" -ne 0 ]]; then
  echo "orvex-marker-check: MISMATCH" >&2
  exit 1
fi

echo "orvex-marker-check: OK ($MARKER_COUNT/$NOOP_COUNT markers, real-set '$REAL_SET_COMMITTED')"
